/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bolao.view.adm;

import bolao.controler.ControlTime;
import bolao.model.bean.Apostador;
import bolao.model.bean.Jogo;
import java.text.ParseException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author RAFAELDEOLIVEIRABAHI
 */
public class TelaListaResultados extends javax.swing.JFrame {

    DefaultTableModel modelo;
    private JFrame parent;
    private String data = null;

    /**
     * Creates new form TelaGerarResultado
     */
    public TelaListaResultados() {
        initComponents();
        readJTable(data);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        try {
            MaskFormatter mascara = new MaskFormatter("##/##/####");
            mascara.setPlaceholderCharacter('_');
            jFormattedTextField1 = new javax.swing.JFormattedTextField(mascara);
            logo = new javax.swing.JLabel();
            imageFundo = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("Resultados");
            setIconImage(new ImageIcon("view\\frame.png").getImage());
            setResizable(false);

            jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jButtonBuscar.setText("Buscar");
            jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonBuscarActionPerformed(evt);
                }
            });
            jPanel1.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 160, 40));

            jTableUser.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "Identificador", "Jogo", "Placar", "Data"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane1.setViewportView(jTableUser);
            if (jTableUser.getColumnModel().getColumnCount() > 0) {
                jTableUser.getColumnModel().getColumn(0).setMinWidth(100);
                jTableUser.getColumnModel().getColumn(0).setPreferredWidth(100);
                jTableUser.getColumnModel().getColumn(0).setMaxWidth(100);
                jTableUser.getColumnModel().getColumn(1).setMinWidth(250);
                jTableUser.getColumnModel().getColumn(1).setPreferredWidth(250);
                jTableUser.getColumnModel().getColumn(1).setMaxWidth(250);
            }

            jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 590, 190));

            jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(255, 255, 255));
            jLabel1.setText("Data:");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 30));

        } catch (ParseException e) {
            e.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, -1));

        logo.setIcon(new ImageIcon("view\\Logo.png"));
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 5, -1, -1));

        imageFundo.setIcon(new javax.swing.ImageIcon("view\\ImageFundo.jpg"));
        jPanel1.add(imageFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 624, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        data = jFormattedTextField1.getText();
        readJTable(data);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void readJTable(String data) {

        modelo = (DefaultTableModel) jTableUser.getModel();
        modelo.setNumRows(0);

        for (Jogo jogo : Apostador.verifyResult(data)) {
            modelo.addRow(new Object[]{
                jogo.getIdentificador(),
                ControlTime.parseTime(jogo.getIdentificador()),
                jogo.getResultado(),
                jogo.getData()
            });
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageFundo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
